### ISSUE TITLE
CS1_COMMANDER vs COMMANDER

### ISSUE THREAD

**Issue by Darkneon** [spaceconcordia/space-commander#17]
https://github.com/spaceconcordia/space-commander/blob/master/src/update-command.cpp#L66

Uses COMMANDER while the rest of the function uses CS1_COMMANDER. 

Is that a typo? If not, what's the difference between the two?

**Comment by SpaceShawn** [comment]
The COMMANDER one is a typo. There are constants defined in space-lib/include/SpaceDecl.h that we use to keep IDs and subsystem names more consistent and manageable. Harley could you please change this?

Thanks

**Comment by harley1011** [comment]
Done
