### ISSUE TITLE
Please make ParseResult of GetLogCommand and DeleteLogCommand static

### ISSUE THREAD

**Issue by Darkneon** [spaceconcordia/space-commander#18]
So that they remain consistent with the rest.

**Comment by harley1011** [comment]
Joseph, can I revert these commands methods back to static? Or are we not using static methods and rather the user has to create the object to invoke the method for the command.

**Comment by SpaceShawn** [comment]
@harley1011 please follow this wiki page for ParseResult definition

https://sites.google.com/a/spaceconcordia.ca/documentation/home/consat-1/subsystems/software/projects/commander/parseresult

**Comment by SpaceShawn** [comment]
@harley1011 the issue of static ParseResult has been settled, they will not be made static. The explanation and specification can be found here:

https://sites.google.com/a/spaceconcordia.ca/documentation/home/consat-1/subsystems/software/projects/commander/parseresult

Can you please read this and begin a new branch for the changes? 

Thanks!
Shawn

**Comment by harley1011** [comment]
Will do.
