### ISSUE TITLE
[settime] tests need root

### ISSUE THREAD

**Issue by CandyRedTele** [spaceconcordia/space-commander#24]
find a way to test settime command without being root. (Mock the system call?)
or at least the tests shouldn't silently succeed if not root.

**Comment by harley1011** [comment]
I have already looked into this quite a bit and I couldn't find a way to easily test it without being root. I don't think it make sense to spend anymore time on this, we know it works you just have to be root to set the time of your machine and mocking the system call just seems overkill for this system call that is relatively simple.

**Comment by SpaceShawn** [comment]
Please make the tests fail if not root. We don't want implicit knowledge in the tests

**Comment by harley1011** [comment]
This looks like it has been resolved can it be closed?

**Comment by CandyRedTele** [comment]
Yes, maybe we can keep them as is, but in the future I suggest that we *mock* system calls in unit tests. Because the goal of a Unit Test is to test the logic of the code in isolation, not its interaction with other module/system.
